import type { HomeAssistant } from "./types";
export function language(
  hass?: Pick<HomeAssistant, "language" | "locale">,
): string {
  const value = (hass?.language || hass?.locale?.language || "en")
    .replace(/_/g, "-")
    .toLowerCase();
  if (/^(nb|nn|no)(-|$)/.test(value)) return "nb-NO";
  try {
    return Intl.getCanonicalLocales(value)[0] ?? "en";
  } catch {
    return "en";
  }
}
const en = {
  off: "Off",
  hvacHeat: "Heating",
  cool: "Cooling",
  heat_cool: "Heating/cooling",
  dry: "Dry",
  fan_only: "Fan only",
  "24h": "24 hours",
  "7d": "7 days",
  "30d": "30 days",
  invalidValue: "Invalid value",
  title: "Heat pump",
  comfort: "Comfort",
  water: "Hot water",
  efficiency: "Efficiency",
  heating: "Heating",
  current: "Room",
  target: "Target",
  mode: "Operating mode",
  flow: "Flow",
  flowTarget: "Flow target",
  outdoor: "Outdoors",
  pressure: "Pressure",
  tank: "Tank temperature",
  tankHint: "Temperature relative to target, not remaining water volume.",
  boost: "Boost hot water",
  boosting: "Boost active · stop",
  quickVeto: "Warmer for a while",
  startVeto: "Start temporary override",
  duration: "Duration (hours)",
  vetoHint: "Uses the temperature above for the selected duration.",
  curve: "Heating curve",
  minFlow: "Minimum flow temperature",
  curveHint: "Changes affect heating over several hours.",
  legionella: "Legionella protection",
  lastReached: "Last reached",
  daysAgo: "days ago",
  today: "today",
  overdue: "Past the reminder interval",
  neverReached: "No temperature-reached date reported",
  futureDate: "Reported date is in the future",
  fault: "Heat pump needs attention",
  details: "Open details",
  stale: "Stale",
  lastSeen: "last seen",
  unknown: "Unknown",
  loading: "Loading…",
  history: "History",
  historyTitle: "Heat pump history",
  historyFailed: "Could not load history",
  noHistory: "No history for this period",
  close: "Close",
  now: "Now",
  retry: "Retry",
  unavailable: "Unavailable",
  pending: "Sending…",
  sent: "Sent · waiting for device update",
  failed: "Could not update",
  range: "Value is outside the permitted range or step",
  invalidMode: "Unsupported operating mode",
  cop: "Measured COP",
  electric: "Electricity in",
  environment: "Environment",
  heat: "Heat out",
  balance: "Reported energy balance",
  noOperation: "No recorded operation in this period",
  noInput: "Heat reported without measured electricity; COP is undefined.",
  missingStats: "No paired energy statistics available",
  partial: "Paired hourly coverage",
  plot: "COP and outdoor temperature",
  plotEmpty: "No matching outdoor-temperature history",
  plotHint:
    "Each point is one paired hour. COP alone does not establish the best heating curve.",
  recorderHint:
    "Recorder counters: late cloud updates can distort hourly points.",
  externalHint: "myVAILLANT hourly statistics",
  through: "Complete hours through",
  chooseEntry: "Choose a myVAILLANT entry or climate entity in the editor.",
  invalidAnchor:
    "The climate entity must belong to the selected myVAILLANT entry.",
  noEntities: "No enabled myVAILLANT entities found for this entry.",
  ambiguous: "Some roles need an explicit entities override",
  noRoles: "No matching entities for this panel.",
  statisticsError: "Could not load statistics",
  registryError: "Could not load entity discovery",
  disconnected: "Home Assistant disconnected",
  appearance: "Appearance",
  window: "COP window",
  entry: "Config entry ID",
  entity: "Climate entity",
  name: "Title",
  all: "All panels",
  default: "Default",
  bubble: "Bubble",
  show_efficiency: "Show efficiency",
  show_hot_water: "Show hot water",
  allow_curve_edit: "Allow heating curve edits",
  legionella_interval_days: "Legionella reminder interval (days)",
  auto: "Automatic",
  editorHint:
    "Select a climate entity or paste an entry ID. Optional role overrides remain available in YAML.",
  noLastSeen: "No last-known reading",
  hours: "h",
  energyNote: "Energy values cover matching valid hours only.",
  statisticsStale: "Previously loaded statistics",
  config: "Configuration",
  season: "Heating or cooling",
  cooling_entity: "Heating/cooling switch (on = cooling)",
  coolingMissing: "Heating/cooling switch not found",
};
const nb: typeof en = {
  off: "Av",
  hvacHeat: "Oppvarming",
  cool: "Kjøling",
  heat_cool: "Oppvarming/kjøling",
  dry: "Avfukting",
  fan_only: "Bare vifte",
  "24h": "24 timer",
  "7d": "7 dager",
  "30d": "30 dager",
  invalidValue: "Ugyldig verdi",
  title: "Varmepumpe",
  comfort: "Komfort",
  water: "Varmtvann",
  efficiency: "Effektivitet",
  heating: "Oppvarming",
  current: "Rom",
  target: "Ønsket",
  mode: "Driftsmodus",
  flow: "Turtemperatur",
  flowTarget: "Ønsket turtemperatur",
  outdoor: "Utendørs",
  pressure: "Trykk",
  tank: "Tanktemperatur",
  tankHint:
    "Temperatur i forhold til ønsket verdi, ikke gjenværende vannmengde.",
  boost: "Ekstra varmtvann",
  boosting: "Ekstra varmtvann aktivt · stopp",
  quickVeto: "Varmere en stund",
  startVeto: "Start midlertidig overstyring",
  duration: "Varighet (timer)",
  vetoHint: "Bruker temperaturen over i valgt tidsrom.",
  curve: "Varmekurve",
  minFlow: "Minste turtemperatur",
  curveHint: "Endringer påvirker oppvarmingen over flere timer.",
  legionella: "Legionellabeskyttelse",
  lastReached: "Sist nådd",
  daysAgo: "dager siden",
  today: "i dag",
  overdue: "Påminnelsesintervallet er overskredet",
  neverReached: "Ingen dato for oppnådd temperatur",
  futureDate: "Rapportert dato er i fremtiden",
  fault: "Varmepumpen trenger oppmerksomhet",
  details: "Åpne detaljer",
  stale: "Utdatert",
  lastSeen: "sist sett",
  unknown: "Ukjent",
  loading: "Laster…",
  history: "Historikk",
  historyTitle: "Varmepumpehistorikk",
  historyFailed: "Kunne ikke hente historikk",
  noHistory: "Ingen historikk for denne perioden",
  close: "Lukk",
  now: "Nå",
  retry: "Prøv igjen",
  unavailable: "Utilgjengelig",
  pending: "Sender…",
  sent: "Sendt · venter på oppdatering fra enheten",
  failed: "Kunne ikke oppdatere",
  range: "Verdien er utenfor tillatt område eller trinn",
  invalidMode: "Driftsmodusen støttes ikke",
  cop: "Målt COP",
  electric: "Strøm inn",
  environment: "Omgivelsesenergi",
  heat: "Varme ut",
  balance: "Rapportert energibalanse",
  noOperation: "Ingen varmedrift registrert i perioden",
  noInput: "Varme rapportert uten målt strømforbruk; COP er ikke definert.",
  missingStats: "Ingen sammenfallende energistatistikk tilgjengelig",
  partial: "Dekning av sammenfallende timer",
  plot: "COP og utetemperatur",
  plotEmpty: "Ingen sammenfallende historikk for utetemperatur",
  plotHint:
    "Hvert punkt er én sammenfallende time. COP alene avgjør ikke riktig varmekurve.",
  recorderHint:
    "Recorder-tellere: forsinkede skyoppdateringer kan forvrenge timepunktene.",
  externalHint: "Timestatistikk fra myVAILLANT",
  through: "Hele timer frem til",
  chooseEntry:
    "Velg en myVAILLANT-oppføring eller klimaenhet i redigeringsverktøyet.",
  invalidAnchor: "Klimaenheten må tilhøre den valgte myVAILLANT-oppføringen.",
  noEntities:
    "Ingen aktiverte myVAILLANT-enheter funnet for denne oppføringen.",
  ambiguous: "Noen roller trenger eksplisitt entities-konfigurasjon",
  noRoles: "Ingen samsvarende enheter for dette panelet.",
  statisticsError: "Kunne ikke laste statistikk",
  registryError: "Kunne ikke finne enheter",
  disconnected: "Home Assistant er frakoblet",
  appearance: "Utseende",
  window: "COP-periode",
  entry: "ID for konfigurasjonsoppføring",
  entity: "Klimaenhet",
  name: "Tittel",
  all: "Alle paneler",
  default: "Standard",
  bubble: "Bubble",
  show_efficiency: "Vis effektivitet",
  show_hot_water: "Vis varmtvann",
  allow_curve_edit: "Tillat endring av varmekurve",
  legionella_interval_days: "Påminnelsesintervall for legionella (dager)",
  auto: "Automatisk",
  editorHint:
    "Velg en klimaenhet eller lim inn oppførings-ID. Roller kan overstyres i YAML.",
  noLastSeen: "Ingen sist kjente måling",
  hours: "t",
  energyNote: "Energiverdiene gjelder bare sammenfallende gyldige timer.",
  statisticsStale: "Tidligere lastet statistikk",
  config: "Konfigurasjon",
  season: "Varme eller kjøling",
  cooling_entity: "Bryter for varme/kjøling (på = kjøling)",
  coolingMissing: "Fant ikke bryteren for varme/kjøling",
};
export type TextKey = keyof typeof en;
export function localize(language: string | undefined, key: TextKey): string {
  return /^(nb|nn|no)(-|$)/.test(
    (language ?? "").replace(/_/g, "-").toLowerCase(),
  )
    ? nb[key]
    : en[key];
}

export function modeLabel(locale: string, mode: string): string {
  if (mode === "heat") return localize(locale, "hvacHeat");
  return ["off", "auto", "cool", "heat_cool", "dry", "fan_only"].includes(mode)
    ? localize(locale, mode as TextKey)
    : mode;
}
